### ISSUE TITLE
3talk 로고를 만들어주세요!

### ISSUE THREAD

**Issue by 3people** [roasted-penguin/3talk#11]

**Comment by sujeong1217** [comment]
일단 임시로 수박로고로 바꾸고 상황에 따라 다시 바꾸겠습니다

**Comment by dudejrs** [comment]
수정씨가 작업하신 로고로 확정짓고 사용하고

제가 작업한 로고는 여기에 올려놓겠습니다.


![무제-1](https://user-images.githubusercontent.com/43363650/59141114-63b60c00-89e2-11e9-830b-c85d46771107.jpg)
![무제-2](https://user-images.githubusercontent.com/43363650/59141122-6e70a100-89e2-11e9-92a8-30cc016e93e2.jpg)
![무제-3](https://user-images.githubusercontent.com/43363650/59141124-74668200-89e2-11e9-93bc-0df2490a73fe.jpg)
![무제-4](https://user-images.githubusercontent.com/43363650/59141126-78929f80-89e2-11e9-822b-9d09e3dc3d8c.jpg)
