### ISSUE TITLE
코드파일과 별개로 토론내용을 저장하는 폴더를 만들고 거기에 토론내용을 저장

### ISSUE THREAD

**Issue by 3people** [roasted-penguin/3talk#4]
github사용빈도도 중요하니깐 그때 그때 떠오르는 아이디어를 하나의 폴더를 만들어서 거기에 올리는게 어떨지 일단은 예시로 만들어서 풀리퀘만 만들어 볼게요

**Comment by sujeong1217** [comment]
좋아요! 추가적으로 회의 때마다 이슈를 생성해 매번 각자 알아온 내용을 커밋해서 같이 모아두면 더 좋지 않을까요?
