### ISSUE TITLE
[IDEA] 채팅 앱 아키텍쳐에 관한 의견 및 중간 진행상황입니다.

### ISSUE THREAD

**Issue by dudejrs** [roasted-penguin/3talk#9]
[아이디어] 

아래와 같은 채팅 앱 아키텍쳐로 간단한 웹 서비스를 구현 할 수 있을 것 같다는 생각이 되었습니다. (아직은 검증은 안됬습니다.)

발표를 할때 커맨드창을 세개 띄어서 Vue 서버,   Express 서버 , MongoDB 서버를 로컬로 한컴퓨터에 세개다 돌려서 구현을 할 수 있지 않을까라는  아이디어입니다.  

Express 서버는 DB서버와  Vue서버사이의 데이터를 중계해주는 MVC모델의 VC역할을 하게되고, Vue서버는 Vue서버의 Data를 받아서 웹브라우저 렌더링 하게 됩니다.

![pbl2](https://user-images.githubusercontent.com/43363650/58754694-1b45ac80-8511-11e9-82b6-6f8d5fbe06e1.jpg)

1. 

제가 어제 몽고DB에 대해서 조금 알아봤습니다.
몽고DB클라우드 서버를 이용하는 계정을 만들어봤는데,
싱가폴에 위치해있는 AWS 서버를 이용 하면 512MB까지 무료로 이용할 수 있는 DB가 만들어집니다.

그리고 mongoDB Compass 라는 프로그램을 다운로드하면 
제 하드웨어의 공간을 이용해서 로컬 서버로 작동 할 수 있는 것 같습니다.

2.  

 그리고 아래 링크를 참고 하여  한번 그 예제대로 따라해봤습니다.

예제를 간략히 설명 하자면, Express 서버에 있는 json 데이터 파일을 Vue서버에 가져와 렌더링
하는 예제입니다. 
간단해서 따라하는데  길어봤자 20분 정도이니  시간 되시면 따라 해보셔도 좋을 것 같습니다  .

[http://vuejs.kr/2017/02/05/express-with-vue/](url)

[문제점]

- 세명씨가 작업하신 파일을 한번 Vue 템플릿을 이용해서 구현해 보려고 했는데, 아직은 socket.io에 대해서 알지 못해서, 구현 못했습니다.
Express를 이용해서 작업하신 거라 Vue서버로 가져올 수 있는 지 확신을 못하겠습니다. Vue-socket.io라는 모듈이 있어서 가능은 할 거 같은데,  다시 구현 하기까지 시간이 오래 걸릴 것 같습니다. 

- 여러명이서 채팅하는건 어떻게 구현 하는지는 더 연구해 봐야 됩니다.

[진행상황 보고]
오늘은 
1. 한번 여기서의 발전방향 
2. Express 몽구스 모듈을 이용해서 MongoDB의 데이터를 가져오는 방법
에 대해서 공부할 예정입니다.

의견있으시면 자유롭게 댓글 달아주세요. 질문도 지적도 달게 받습니다!

**Comment by 3people** [comment]
https://github.com/rexeze/anonymouse-realtime-chat-app

node mongodb express socket.io 쓰는 예젠데 저희가 구현하려는게 다 들어가 있네요..ㅋㅋㅋㅋ
